[package]
name = "lindera-decompress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lzma-rs = "0.2"
serde = { version = "1.0", features = ["derive"]}
bincode = "1.3"
anyhow = "1.0"
