[package]
name = "lindera-dictionary"
version = "0.32.0"
edition = "2021"
description = "A Japanese morphological dictionary."
documentation = "https://docs.rs/lindera-dictionary"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[features]
default = []  # No directories included
ipadic = ["lindera-ipadic/ipadic"]  # Include Japanese dictionary (IPADIC)
ipadic-neologd = ["lindera-ipadic-neologd/ipadic-neologd"]  # Include Japanese dictionary (IPADIC NEologd)
unidic = ["lindera-unidic/unidic"]  # Include Japanese dictionary (UniDic)
ko-dic = ["lindera-ko-dic/ko-dic"]  # Include Korean dictionary (ko-dic)
cc-cedict = ["lindera-cc-cedict/cc-cedict"]  # Include Chinese dictionary (CC-CEDICT)
compress = ["lindera-ipadic/compress", "lindera-ipadic-neologd/compress", "lindera-unidic/compress", "lindera-ko-dic/compress", "lindera-cc-cedict/compress"]  # Compress dictionaries

[dependencies]
anyhow.workspace = true
bincode.workspace = true
byteorder.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

lindera-core.workspace = true
lindera-cc-cedict = { workspace = true, optional = true }
lindera-cc-cedict-builder.workspace = true
lindera-ipadic = { workspace = true, optional = true }
lindera-ipadic-builder.workspace = true
lindera-ipadic-neologd = { workspace = true, optional = true }
lindera-ipadic-neologd-builder.workspace = true
lindera-ko-dic = { workspace = true, optional = true }
lindera-ko-dic-builder.workspace = true
lindera-unidic = { workspace = true, optional = true }
lindera-unidic-builder.workspace = true
