[package]
name = "lindera-dictionary"
version = "1.4.0"
edition = "2024"
description = "A morphological analysis library."
documentation = "https://docs.rs/lindera-dictionary"
homepage = "https://github.com/lindera/lindera"
repository = "https://github.com/lindera/lindera"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[features]
build_rs = ["dep:reqwest"]
compress = []
mmap = ["dep:memmap2"]
train = ["dep:rucrf"]
default = ["compress", "mmap"]

[dependencies]
anyhow.workspace = true
bincode.workspace = true
byteorder.workspace = true
csv.workspace = true
derive_builder.workspace = true
encoding.workspace = true
encoding_rs.workspace = true
encoding_rs_io.workspace = true
flate2 = { workspace = true }
glob.workspace = true
log.workspace = true
md5.workspace = true
memmap2 = { workspace = true, optional = true }
num_cpus.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
reqwest = { workspace = true, optional = true }
rucrf = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tar = { workspace = true }
thiserror.workspace = true
tokio.workspace = true
yada.workspace = true

[dev-dependencies]
rand.workspace = true
tempfile = "3.23.0"
