[package]
name = "lindera-core"
version = "0.6.0"
authors = [
    "Paul Masurel <paul.masurel@gmail.com>",
    "Minoru Osuka <minoru.osuka@gmail.com>",
    "Tomoko Uchida <tomoko.uchida.1111@gmail.com>",
    "Jun Ohtani <johtani@gmail.com>"
    ]
edition = "2018"
description = "A morphological analysis core library."
documentation = "https://docs.rs/lindera-core"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera/lindera-core"
readme = "README.md"
keywords = ["morphological", "analysis", "library"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
bincode = "1.3"
byteorder = "1.3"
encoding = "0.2"
serde = {version="1.0", features = ["derive"] }
yada = "0.3"
