[package]
name = "lindera-ipadic"
version = "0.6.1"
authors = [
    "Paul Masurel <paul.masurel@gmail.com>",
    "Minoru Osuka <minoru.osuka@gmail.com>",
    "Tomoko Uchida <tomoko.uchida.1111@gmail.com>",
    "Jun Ohtani <johtani@gmail.com>"
    ]
edition = "2018"
description = "A Japanese morphological dictionary loader for IPADIC."
documentation = "https://docs.rs/lindera-ipadic"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera/lindera-ipadic"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "loader", "ipadic"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
bincode = "1.3"
byteorder = "1.3"

lindera-core = { version = "0.6", path = "../lindera-core" }

[build-dependencies]
flate2 = "1.0"
reqwest = "0.10"
tar = "0.4"
tokio = { version = "0.2", features = ["full"] }

lindera-ipadic-builder = { version = "0.6", path = "../lindera-ipadic-builder" }
