[package]
name = "lindera-unidic-builder"
version = "0.12.2"
edition = "2021"
description = "A Japanese morphological dictionary builder for UniDic."
documentation = "https://docs.rs/lindera-unidic-builder"
homepage = "https://github.com/lindera-morphology/lindera-unidic-builder"
repository = "https://github.com/lindera-morphology/lindera-unidic-builder"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "builder", "unidic"]
categories = ["text-processing"]
license = "MIT"

[features]
compress = ["lindera-compress"]

[dependencies]
anyhow = "1.0"
bincode = "1.3"
byteorder = "1.4"
clap = { version = "3.1", features = ["derive"] }
csv = "1.1"
encoding = "0.2"
env_logger = "0.9"
glob = "0.3"
log = "0.4"
yada = "0.5"

lindera-core = { version = "0.12.2", path = "../lindera-core" }
lindera-decompress = { version = "0.12.2", path = "../lindera-decompress" }
lindera-compress = { version = "0.12.2", path = "../lindera-compress", optional = true }

[[bin]]
name = "lindera-unidic-builder"
path = "src/main.rs"
