[package]
name = "lindera-cc-cedict-builder"
version = "0.13.1"
edition = "2021"
description = "A Chinese morphological dictionary builder for CC-CEDICT."
documentation = "https://docs.rs/lindera-cc-cedict-builder"
homepage = "https://github.com/lindera-morphology/lindera-cc-cedict-builder"
repository = "https://github.com/lindera-morphology/lindera-cc-cedict-builder"
readme = "README.md"
keywords = ["chinese", "morphological", "dictionary", "builder", "cc-cedict"]
categories = ["text-processing"]
license = "MIT"

[features]
compress = ["lindera-compress"]

[dependencies]
anyhow = "1.0"
bincode = "1.3"
byteorder = "1.4"
clap = { version = "3.1", features = ["derive"] }
csv = "1.1"
encoding = "0.2"
env_logger = "0.9"
glob = "0.3"
log = "0.4"
yada = "0.5"

lindera-core = { version = "0.13.1", path = "../lindera-core" }
lindera-decompress = { version = "0.13.1", path = "../lindera-decompress" }
lindera-compress = { version = "0.13.1", path = "../lindera-compress", optional = true }

[[bin]]
name = "lindera-cc-cedict-builder"
path = "src/main.rs"
