[package]
name = "lindera-wasm"
version = { workspace = true }
edition = { workspace = true }
description = "A morphological analysis library for WebAssembly."
documentation = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = "README.md"
keywords = ["morphological", "analysis", "library", "wasm", "webassembly"]
categories = ["text-processing"]
license = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
embed-ipadic = ["lindera/embed-ipadic"] # Embed IPADIC dictionary (Japanese)
embed-unidic = ["lindera/embed-unidic"] # Embed UniDic dictionary (Japanese)
embed-ko-dic = ["lindera/embed-ko-dic"] # Embed ko-dic dictionary (Korean)
embed-cc-cedict = [
    "lindera/embed-cc-cedict",
] # Embed CC-CEDICT dictionary (Chinese)
embed-cjk = [
    "lindera/embed-cjk",
] # Embed IPADIC dictionary (Japanese), ko-dic dictionary (Korean), CC-CEDICT dictionary (Chinese)
default = []

[dependencies]
js-sys = "0.3.85"
once_cell = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = { version = "0.2.108" }

lindera = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
wasm-bindgen-test = "0.3.58"
wasm-bindgen = { version = "0.2.108" }
